language: cpp

dist: xenial
sudo: required

matrix:
  include:
    - name: Static checks (clang-format)
      env: STATIC_CHECKS=yes
      os: linux
      compiler: clang

    - name: Linux module (clang, Godot 3.2)
      env: GDVER="3.2"
      os: linux
      compiler: clang

    - name: Linux module (clang, Godot 4.0)
      env: GDVER="4.0"
      os: linux
      compiler: clang

before_install:
  - echo "deb http://archive.ubuntu.com/ubuntu xenial-updates main restricted universe multiverse" | sudo tee /etc/apt/sources.list.d/xenial-updates.list
  - sudo apt-get update -qq
  - sudo apt -y install libasound2-dev libgl1-mesa-dev libglu1-mesa-dev libx11-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev -q
  - sudo apt -t xenial-updates -y install clang-format-6.0 clang-6.0 -q

install:
  - pip install --user scons;

script:
  - if [ "$STATIC_CHECKS" = "yes" ]; then
      bash ./.scripts/clang_format.sh;
    else
      if [ "$GDVER" = "3.2" ]; then
        bash ./.scripts/module_build_3.sh;
      else
        bash ./.scripts/module_build_4.sh;
      fi
    fi
